#!/bin/bash
# Activate the pixi `ros` environment and the colcon workspace, then hand off.
#
# This used to `source /opt/ros/humble/setup.bash`.  There is no /opt/ros any
# more: ROS 2 Humble comes from RoboStack as conda packages, and activating the
# environment is what sets ROS_DISTRO, AMENT_PREFIX_PATH, RMW_IMPLEMENTATION and
# the library paths.
set -euo pipefail

# Generated by `pixi shell-hook --environment ros` at build time -- the runtime
# image has no pixi binary to regenerate it with.
#
# nounset is off for this for the same reason as the workspace source below:
# RoboStack's activate.d reads CONDA_BUILD without a default.
set +u
source /shell-hook.sh
set -u

echo "========================================"
echo "GroundingDINO ROS 2 Container Starting"
echo "========================================"

if [ -f "${ROS2_WS:-/app/ros2_ws}/install/setup.bash" ]; then
    echo "Sourcing ROS2 workspace..."
    # The workspace overlays the conda environment, so it is sourced second.
    # nounset is off for this: ROS's generated setup scripts read unset
    # variables and would trip `set -u`.
    set +u
    source "${ROS2_WS:-/app/ros2_ws}/install/setup.bash"
    set -u
else
    echo "ERROR: ROS2 workspace not built at ${ROS2_WS:-/app/ros2_ws}/install"
    echo "       The image build should have produced it; this is a build bug."
    exit 1
fi

echo "----------------------------------------"
echo "Environment Information:"
echo "ROS_DISTRO      : ${ROS_DISTRO:-unset}"
echo "ROS_DOMAIN_ID   : ${ROS_DOMAIN_ID:-0 (default)}"
echo "RMW             : ${RMW_IMPLEMENTATION:-default}"
echo "ROS2_WS         : ${ROS2_WS:-/app/ros2_ws}"
echo "PYTHONPATH      : ${PYTHONPATH:-unset}"
# `docker run --user <uid>` with no passwd entry: id -un prints the number and
# still fails, so take the name only when it succeeds.
run_as=$(id -un 2>/dev/null) || run_as="unknown"
echo "Running as      : ${run_as} (uid=$(id -u) gid=$(id -g))"
echo "----------------------------------------"

# The container is non-root so that results land on the host owned by you rather
# than by root.  The flip side: a bind mount we cannot write to stops the node on
# its first write half a minute in.  Two ways that happens -- someone else owns
# it, or we own it and the mode says no -- and the fix differs, so report both
# and say which one applies.
for d in /output "${HOME:-}"; do
    if [ -n "$d" ] && [ -d "$d" ] && [ ! -w "$d" ]; then
        owner=$(stat -c '%u:%g' "$d" 2>/dev/null || echo "?:?")
        mode=$(stat -c '%a' "$d" 2>/dev/null || echo "?")
        echo "ERROR: $d is not writable by uid=$(id -u) gid=$(id -g)"
        echo "       (owned by $owner, mode $mode)"
        echo ""
        if [ "${owner%%:*}" = "$(id -u)" ]; then
            echo "  You already own it, so the mode is what refuses the write."
            echo "  On the host:"
            echo "      chmod u+w /path/to/that/dir"
        else
            echo "  The host directory mounted there belongs to a different user."
            echo "  Either chown it on the host:"
            echo "      sudo chown -R \$(id -u):\$(id -g) /path/to/that/dir"
            echo "  or run the container as its owner:"
            echo "      docker run --user ${owner%%:*}:${owner##*:} ..."
        fi
        exit 1
    fi
done

# Ask torch, not nvidia-smi.  The CUDA runtime here is a conda package rather
# than a toolkit install, so a missing driver shows up as is_available() ==
# False, not as a missing binary.
python - <<'PY'
import torch
if torch.cuda.is_available():
    print(f"CUDA            : {torch.cuda.get_device_name(0)} (torch {torch.__version__})")
else:
    print(f"CUDA            : NOT AVAILABLE (torch {torch.__version__}) -- "
          "start with --gpus all")
PY

# The detector must resolve to the installed package, not to the ./groundingdino
# config directory in the source tree.  It does, because that directory has no
# __init__.py and loses to a regular package -- but the node fails opaquely and
# late if this ever stops being true, so check it here where it is one line.
python -c "import groundingdino, sys; p = groundingdino.__file__ or ''; \
    print(f'detector        : {p}'); \
    sys.exit(0) if 'site-packages' in p else \
    sys.exit(f'groundingdino resolved to {p!r}, not the installed package')"

echo "----------------------------------------"
echo ""

exec "$@"
