#!/bin/bash
# Activate the pixi environment, then hand off.
#
# The ROS entrypoint sourced /opt/ros/humble/setup.bash and a colcon workspace.
# There is neither here; the only thing that needs putting on PATH is the conda
# environment solved from pixi.lock at build time.
set -euo pipefail

# Generated by `pixi shell-hook` in the build stage -- the runtime image has no
# pixi binary to regenerate it with.  It sets PATH, CONDA_PREFIX and the
# activation variables for /app/.pixi/envs/default.
source /shell-hook.sh

echo "========================================"
echo "Selective tracking -- spool worker"
echo "========================================"
echo "spool dir : ${SPOOL_DIR:-/spool}"
echo "weights   : ${GDINO_WEIGHTS:-unset}"
echo "config    : ${GDINO_CONFIG:-unset}"
echo "prompt    : ${GDINO_PROMPT:-unset}"
echo "extra args: ${GDINO_EXTRA_ARGS:-none}"

if [ ! -r "${GDINO_WEIGHTS:-}" ]; then
    echo
    echo "WARNING: weights not readable at '${GDINO_WEIGHTS:-}'."
    echo "         Mount the checkpoint, e.g. -v /path/to/weights:/weights:ro"
    echo "         Every job will fail until it is there."
fi

# torch is what actually decides, so ask it rather than nvidia-smi -- the CUDA
# runtime here comes from conda-forge, not from a toolkit install, and a missing
# driver shows up as `cuda.is_available() == False` rather than a missing binary.
python - <<'PY'
import torch
if torch.cuda.is_available():
    print(f"cuda      : {torch.cuda.get_device_name(0)} "
          f"(torch {torch.__version__})")
else:
    print(f"cuda      : NOT AVAILABLE (torch {torch.__version__}) -- "
          "run with --gpus all; CPU inference is correct but very slow, "
          "and --fp16 must be dropped")
PY

echo "----------------------------------------"
exec "$@"
